FROM python:3.11

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . . 
WORKDIR /usr/src/app/namebazaarBot
EXPOSE 80
CMD [ "python3", "namebazaarBot.py" ]
