FROM python:3.11

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
COPY memefactory_bot/memefactory_bot.py memefactory_bot.py
COPY abi /usr/src/abi
EXPOSE 80
CMD [ "python3", "memefactory_bot.py" ]
