name: docker_test

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  docker_build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: read # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build an image from Dockerfile
        run: |
          docker build -t discord-py-bots:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: discord-py-bots:${{ github.sha }}
          format: "template"
          severity: "CRITICAL,HIGH"
